#!/usr/bin/env bash
# Subset Noto Sans to printable ASCII and embed as C arrays for LVGL Tiny TTF.
set -euo pipefail
TMP=$(mktemp -d)
cd "$(dirname "$0")/.."
SRC=/usr/share/fonts/noto
OUT=fonts.h
echo "// Generated by tools/make_fonts.sh - Noto Sans (SIL OFL 1.1), subset to ASCII" > $OUT
echo "#pragma once" >> $OUT
echo "#include <stdint.h>" >> $OUT
for spec in "Light:font_light" "Medium:font_medium"; do
  w=${spec%%:*}; n=${spec##*:}
  pyftsubset "$SRC/NotoSans-$w.ttf" --unicodes=U+0020-007E,U+00B0,U+00B7,U+2022 \
    --layout-features='tnum,kern' --output-file="$TMP/$n.ttf" 2>/dev/null || \
  pyftsubset "$SRC/NotoSans-$w.ttf" --unicodes=U+0020-007E,U+00B0,U+00B7,U+2022 --output-file="$TMP/$n.ttf"
  echo "alignas(4) static const uint8_t ${n}_data[] = {" >> $OUT
  xxd -i < "$TMP/$n.ttf" >> $OUT
  echo "};" >> $OUT
  echo "static const size_t ${n}_size = sizeof(${n}_data);" >> $OUT
  ls -la "$TMP/$n.ttf"
done
